export const SETUP_URL = 'https://qvik.herokuapp.com/api/v1/initial-setup';
//export const EVENTS_URL = 'https://qvik.herokuapp.com/api/v1/events';
export const EVENTS_URL = 'https://qvik.herokuapp.com/api/v1/events?groupBy=DATE';
export const RESTAURANT_URL = 'https://qvik.herokuapp.com/api/v1/restaurants';
export const PRESENTERS_URL = 'https://qvik.herokuapp.com/api/v1/presenters';
export const STAGES_URL = 'https://qvik.herokuapp.com/api/v1/stages';
export const VENUES_URL = 'https://qvik.herokuapp.com/api/v1/venues';
export const IMAGES_URL = 'https://qvik.herokuapp.com/api/v1/images/';
export const UPDATE_URL = 'https://qvik.herokuapp.com/api/v1/last-update';